### ISSUE TITLE
gpt-4 not working

### ISSUE THREAD

**Issue by r3v3r3seEntropy** [kyang6/llmparser#11]
I have GPT-4 for my open-ai-account but whenever i edit the model to gpt-4 
all result values are null, confidence is null etc. GPT-4 is enabled for my account, i can use gpt-4 with my api keys
  fields: {
    'Patient name': { value: null, source: '', confidence: 0, type: 'string' },
    'Patient age': { value: null, source: '', confidence: 0, type: 'number' },
    'Present illness history': { value: null, source: '', confidence: 0, type: 'string' },
    'Chief complaints': { value: null, source: '', confidence: 0, type: 'string' },
    'Family history': { value: null, source: '', confidence: 0, type: 'string' },
    'Menstrual history': { value: null, source: '', confidence: 0, type: 'string' },
    'Drug history': { value: null, source: '', confidence: 0, type: 'string' }
  }

**Comment by r3v3r3seEntropy** [comment]
Even with the given input,     at SimpleClassifier.<anonymous> (/Users/aritradas/Downloads/test2/node_modules/llmparser/lib/classifier/classification_techniques/simple/simple_classifier.js:57:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/aritradas/Downloads/test2/node_modules/llmparser/lib/classifier/classification_techniques/simple/simple_classifier.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
aritradas@Aritras-MacBook-Air test2 %

**Comment by pditmar** [comment]
Same problem here. "Invalid classification JSON" error.
